apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      name: conv-api
      labels:
        components: backend
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          resources:
            limits:
              memory: "500Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000
              name: one
            - containerPort: 3030
              name: two
          env:
            - name: AMQP_EXCHANGE
              value: conv-image
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_USER
                  name: rabbit-secret
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_PASS
                  name: rabbit-secret
            - name: AMQP_HOSTNAME
              value: rabbit-clusterip
#            - name: VITE_DOMAIN
#              valueFrom:
#                configMapKeyRef:
#                  name: config-map
#                  key: VITE_DOMAIN
          volumeMounts:
            - mountPath: /opt/app/uploads
              name: conv-data
              subPath: data
      volumes:
        - name: conv-data
          persistentVolumeClaim:
            claimName: api-pvc
