apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-clusterip
spec:
  selector:
    components: {{ .Values.api.components }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
  type: ClusterIP
