apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-clusterip
spec:
  selector:
    components: {{ .Values.postgres.components }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
  type: ClusterIP
