---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  AMQP_EXCHANGE: "demo"
  AMQP_USER: "demo"
  AMQP_PASSWORD: "demo"
  AMQP_HOSTNAME: "rabbitmq-clusterip"
  AMQP_QUEUE: "converter"
